[package]
name = "vimscape_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.6.0", features = ["neovim-0-11", "test"] }
# nvim-oxi = "0.6.0"
logos = "0.14.1"
rusqlite = "0.32.1"
serde = "1.0.216"
